import{S,a as v,i as n}from"./assets/vendor-Bd9JIWAl.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const f=document.querySelector(".gallery");document.querySelector(".load-more");const m=document.querySelector(".loader"),E=new S(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const r=o.map(({webformatURL:a,largeImageURL:l,tags:e,likes:t,views:s,comments:b,downloads:w})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${l}">
          <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${s}</p>
          <p><b>Comments:</b> ${b}</p>
          <p><b>Downloads:</b> ${w}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",r),E.refresh()}function q(){f.innerHTML=""}function g(){m.classList.remove("hidden")}function p(){m.classList.add("hidden")}const P="49601023-171b06d69188b97ef0963e347",M="https://pixabay.com/api/";async function h(o,r=1){try{return(await v.get(M,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}catch(a){throw console.error("Error fetching images:",a),a}}const $=document.querySelector(".form"),B=document.querySelector('[name="search-text"]'),u=document.getElementById("load-more");let c="",i=1,d=0;$.addEventListener("submit",async o=>{if(o.preventDefault(),c=B.value.trim(),i=1,!c){n.error({title:"Error",message:"Please enter a search query."});return}g(),q(),L();try{const{hits:r,totalHits:a}=await h(c,i);d=a,r.length===0?n.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"}):(y(r),d>15&&O())}catch{n.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{p()}});u.addEventListener("click",async()=>{i+=1,g();try{const{hits:o}=await h(c,i);y(o),i*15>=d&&(L(),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{p()}});function O(){u.classList.remove("hidden")}function L(){u.classList.add("hidden")}
//# sourceMappingURL=index.js.map
