import{S,a as v,i as n}from"./assets/vendor-Bd9JIWAl.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const f=document.querySelector(".gallery");document.querySelector(".load-more");const m=document.querySelector(".loader"),E=new S(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:a,largeImageURL:l,tags:e,likes:r,views:s,comments:L,downloads:w})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${l}">
          <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${s}</p>
          <p><b>Comments:</b> ${L}</p>
          <p><b>Downloads:</b> ${w}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),E.refresh()}function q(){f.innerHTML=""}function g(){m.classList.remove("hidden")}function h(){m.classList.add("hidden")}const P="49601023-171b06d69188b97ef0963e347",B="https://pixabay.com/api/";async function p(o,t=1){try{return(await v.get(B,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch(a){throw console.error("Error fetching images:",a),a}}const M=document.querySelector(".form"),$=document.querySelector('[name="search-text"]'),u=document.getElementById("load-more");let c="",i=1,d=0;M.addEventListener("submit",async o=>{if(o.preventDefault(),c=$.value.trim(),i=1,!c){n.error({title:"Error",message:"Please enter a search query."});return}g(),q(),O(),b();try{const{hits:t,totalHits:a}=await p(c,i);d=a,t.length===0?n.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"}):(y(t),d>15&&x())}catch{n.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{h()}});u.addEventListener("click",async()=>{i+=1,g();try{const{hits:o}=await p(c,i);y(o);const t=Math.ceil(d/15);i>=t&&(b(),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{h()}});function O(){const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}function x(){u.classList.remove("hidden")}function b(){u.classList.add("hidden")}
//# sourceMappingURL=index.js.map
